[book]
authors = ["DiracLee"]
language = "zh-CN"
title = "Rust 时刻(Rust Time)"
src = "src"

[output.html]
additional-css = ["theme/style3.css"]
additional-js = ["assets/custom.js", "assets/bigPicture.js"]

[output.html.playground]
editable = true
copy-js = true
line-numbers = true

[output.html.fold]
enable = true
level = 1

[rust]
edition = "2021"   #在线运行用2021版本的
